git-pile/git-pile

- git_pile/git_pile.py
When the old and new baselines do not match, we don't generate an
"overall diff" since that can be potentially way too big. In that case,
don't print an annoying "None" at the end.
> format-patch: fix printing "None" at the end

- git_pile/git_pile.py
Addition of arguments to genbranch needs to be carried for am, for when
it's called with the -g argument.
> am: fix integration with genbranch

- git_pile/git_pile.py
Allow any directory in the pile branch without giving a warning. It may
be useful to allow project-specific configuration there.
Also allow any file or directory starting with '.', which is useful when
integrating with CI or other tools that add configuration on hidden
files.
> setup: don't warn on directories and hidden files

- git_pile/git_pile.py
Just open it as a single message. Earlier we needed to support splitting
an mbox because the only interface Patchwork would give us was to
download the patch series with cover. Now patchwork has support to
download only the cover, so we don't have to try to split the mbox
anymore.
This fixes an issue with mailbox.mbox() erroneously splitting the mbox
in the first occurrence of "^From" in the body of the message.
Fix: #19
> Dot not try to split mbox

- git_pile/__init__.py
This allows to identify we are using a development version, without much more information. I thought about adding the output of `git describe --tags`, but there is more trouble than it's worth... we'd need to do different things depending if we are executing from git repo or not. So: just add a "+" to indicate it's e.g. 0.96+.
This is quite handy with `pip3 install --user -e ~/p/git-pile` as we can have a "installed version" that is simply executing from the git repository.
> Set version as development

- git_pile/git_pile.py
This changes the arguments to `git am` so the commits generated by applying the patches have the same SHAs if the baseline is the same and the patches are the same.
If the baseline is the same between 2 invocations of `git pile genbranch` the other 2 variables that are accounted for during the hash calculation are: the committer date, committer name and commiter's email. Now we can set these to fixed values: name and email we read from config; date we consider the same as author's.
This allows the generated branch to have the same git objects after multiple invocations, even if done by different developers.
> Allow genbranch to generate the same commits over multiple invocations

- git_pile/git_pile.py
- git_pile/helpers.py
As detailed in #25, this switches the login in git-pile so when sending a patch series, only patches considered as "added" are actually sent. Review for modified patches are better handled in the cover letter with the interdiff or in the separate "REVIEW" patch.
In order to ease the cover letter review this also reorders the files we show up there.
> Teach format-patch to only add new patches

- git_pile/git_pile.py
This allows to tweak what git-range-diff considers as a new commit vs a
modified one.
Close: #29
> format-patch: allow to pass creation-factor

- git_pile/git_pile.py
Since now we consider the review patch as part of the patch series, we
need to correctly account for its absence when we skip its generation.
> format-patch: fix patch number when baseline changes

- git_pile/git_pile.py
--allow-local-pile-commits was made long because initially there was no
real use case for it. However it turns out this is useful when iterating
a new version of the patch and you have to fix conflicts while running
`git genbranch -i` command so you can easily get pile and result-branch
back in sync.
> Allow --local instead of --allow-local-pile-commits

- git_pile/git_pile.py
If the end result is empty (just reordering patches etc), the REVIEW
patch will be an empty patch. Patchwork doesn't parse empty patches as
patches if the content-type is text/plain, but using text/x-diff
forces it to grab the whole email as the patch. We don't need to care
what ends up in the patch as far as patchwork is concerned, as no one
needs to feed that patch as such back to git, only the cover letter is
used.
Signed-off-by: Petri Latvala <petri.latvala@intel.com>
> format-patch: Set the REVIEW patch content type to text/x-diff

- git_pile/__init__.py
pip complains that it doesn't follow PEP 440:
WARNING: Built wheel for git-pile is invalid: Metadata 1.2 mandates PEP
440 version, but '0.97-' is not
> version: do not use '+' in the version

- git_pile/git_pile.py
Allow user to always store patches from format-patch to a default
directory, set in the config file. Previously we would default to CWD if
not argument was passed, now we have the following priority:
cmdline -> config -> CWD
Also fix copy and paste mistake in the help message: the requirement for
--force is from the genpatches command, not from format-patch.
> format: add config entry for output directory

- git_pile/git_pile.py
git >= 2.28 has a setting that the user may have set to change the
default branch used by git-init. This was due to projects moving out of
"master" branch and calling it something else, like "main".
When we do a temporary repo to initialize an orphan pile branch, let's
give "pile" as the branch name explicitly: "master" may not be the
default branch and we would then fail when we fetch the temporary repo.
> init: Give an explicit branch name on git-init

- git_pile/git_pile.py
Add support for passing --whitespace=fix to git am (and thus git apply)
to fix whitespace while generating the branch.
An alternative might be to support passing arbitrary options, but that probably opens up a lot of opportunities for the user to shoot themselves in the foot.
> genbranch: add --fix-whitespace option to fix whitespace at git am

- git_pile/git_pile.py
- git_pile/helpers.py
Using this in https://github.com/git-pile/playground/commit/5e2f503aba810853eb051b4e7d38b8f96cb723ee
It's useful for when we already have the commit message somewhere else.
> format-patch: allow cover message from file/stdin

- git_pile/git_pile.py
- git_pile/helpers.py
When a patch doesn't apply, several times it's just because the line
numbers in the diff hunks changed. A lazy resolution is to take either
side and eventually fix things up when doing genbranch. I've been using
this manually and it speeds up a lot when applying patches with
conflicts. Even in the case we can't solve them all, it already helps
as we will likely have those kind of conflicts.
My implementation idea was to do something much simpler:
return git_can_fail(["-C", patchesdir,
"-c", "mergetool.diffhunkkeeptheirs.cmd=\"sed -i -e '/^<<<<<<< HEAD/ {N;N;N;N; s/<<<<<<< HEAD.*\\n@@.*\\n=======.*\\n\\(@@.*\\)\\n>>>>>>>.*/\\1/g}' ${MERGED}\"",
"-c", "mergetool.diffhunkkeeptheirs.trustExictCode=true",
"-c", "mergetool.keepBackup=false",
"mergetool", "-y",  "--tool=diffhunkkeeptheirs"], …
> am: add option to fallback to "fuzzy" apply

- git_pile/git_pile.py
Two useful options while generating patches:
1. Allow to add our signoff to the cover
2. Parse the -v / --reroll-count option, just like git-format-patch
> genbranch: add -v and --signoff

- git_pile/git_pile.py
This speeds up the genpatch() implementation (and by consequence the
format-patch subcommand). We don't need to fork one git-format-patch for
each commit. We can just operate on the range with a single fork and
later fixup the filename, just like we fixup the Subject line.
On a big repository like the Linux kernel, with ~2300 patches managed by
the pile and a non-trivial change, these are the numbers:
Before: 3m35.559s
After: 33.302s
> genpatches: speedup patch generation

- git_pile/git_pile.py
We can't use text/plain since patchwork would otherwise wait
indefinitely for the last patch. However looking at b4, it uses
text/plain and text/x-patch. Try to switch to x-patch instead of using
x-diff for improved compatibility.
> format-patch: switch last patch to text/x-patch

- git_pile/__init__.py
- git_pile/git_pile.py
Allow to reset just the pile instead of synchronizing both branches.
This is a shortcut to:
cd patches
git rev-parse HEAD
git reset --hard pile@{u}
The commands above, or variants thereof, are common when we are going to
generate a v2 of a patch series and for that we apply the previous
version from somewhere. Commands for a v2 are more or less like:
git pile am /tmp/v1.mbx
git pile genbranch -i
r=$(git -C patches rev-parse HEAD)
git -c patches reset --hard HEAD^
git pile format-patch -v2 -C $r
This now can be done with:
git pile am /tmp/v1.mbx
git pile genbranch -i
git pile reset -p
git pile format-patch -v2 -C <paste>
In which paste is simply what we gave in the output of `reset -p`.
> reset: add --pile-only

- git_pile/git_pile.py
When the .git repo is located outside the work tree by using a bare repo, git-pile was failing
to setup the branches/config. Change the behavior so we are gone with the concept of "main checkout":
Now each command is expected to be given in the right worktree, which is more in line with
other git subcommands.
There may be still some rough edges to cover and some cleanup to do, but this is at least a good start.
Fix: #65
> Fix git repo outside of work tree

- git_pile/git_pile.py
Besides the warnings we see when applying the interdiff, if the user has
configured apply.whitespace=strip, the final patch saved in the pile
will be corrupted. This causes a subsequent genbranch to fail due to
malformed patch. Critical here is to override the config during
git-pile-am phase, but to make sure the result branch is the same
regardless of configuration, let's override it in genbranch too.
> Override whitespace config

- git_pile/git_pile.py
$ git am bla.patch
... conflicts
$ git pile am cover.patch
fatal: Already on an am or rebase operation
That's because we are checking the wrong worktree. We have to check if
the worktree where pile is checkout is in the middle of am, not whatever
worktree we are on currently. This now becomes:
$ git pile am .git/p/v2-0000-cover-letter.patch
‣ Entering 'patches' directory
fatal: Already on am or rebase operation in worktree /home/lucas/p/linux/patches
> am: Fix checking pending am in the wrong worktree

- git_pile/git_pile.py
Allow to open the editor to modify the cover letter as soon as
format-patch returns succesfully. This can be either set in the command
line with --[no-]compose|--[no-]edit or set in the configuration with
`git config pile.format-compose true`, to make it the default behavior.
If no configured and not set in the command line, default is not to open
the editor.
Editor chosen follows the same logic git uses: see git-var(1).
Fix: #63
> format: Add --compose|--edit

- git_pile/git_pile.py
Allow th user to override format-patch behavior of filtering the cover letter by
the list of patches that appear in the git-range-diff output.
Do not filter out patches that have changes on diff hunk numbers only.  To
reduce the diff and possible conflicts with other patch series, git-pile by
default filters out changes to patches that only change the line numbers as
recorded in the diff hunk headers.
For some rare cases in which a patch to a file removes a large number of lines,
and another patch on top changes lines nearby, this may fail. Passing
--no-range-diff-filter option allows git-pile to output the full diff in the
cover letter, as if git-pile genpatches had been called, avoiding the issue.
> format-patch: add --no-range-diff-filter

- git_pile/git_pile.py
When passing 2 ranges to git pile format-patch it was complaining about
the first argument if the new baseline was invalid. It needs to complain
about first argument if old baseline or old ref
(<old_baseline>..<new_ref>) is invalid. Otherwise the problem was in the
second argument.
> format-patch: Fix range on error message

- git_pile/git_pile.py
It's useful when doing rebases of the pile in a new baseline: in this
cases we pass as argument:
git pile format-patch <oldbaseline>..<oldtip> <newbaseline>..<newtip>
... so the correct diff and cover letter are calculated.
To get the "oldbaseline" we could do:
eval $(git show oldpile:config)
echo $BASELINE
Let `git pile baseline <oldpile>` be a shortcut for that.
> baseline: support passing ref as argument

- setup.py
This makes packaging easier on distros where the default location for Bash completions is somewhre else (for example in /usr/share/bash-completion/completions).
> Make Bash completions configurable from env vars

- git_pile/git_pile.py
$ git pile am /tmp/ambox
fatal: [Errno 2] No such file or directory: '/tmp/ambox'
This is less scary than
$ git pile am -s pile-commit /tmp/.ambox
Traceback (most recent call last):
File "/home/lucas/.local/bin/git-pile", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File "/home/lucas/p/git-pile/git-pile", line 12, in <module>
sys.exit(git_pile.main(*sys.argv[1:]))
File "/home/lucas/p/git-pile/git_pile/git_pile.py", line 2190, in main
return args.func(args)
File "/home/lucas/p/git-pile/git_pile/git_pile.py", line 1054, in cmd_am
cover = PileCover.parse(args.mbox_cover)
File "/home/lucas/p/git-pile/git_pile/git_pile.py", line 885, in parse
oldf = open(fname, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.ambox'
Signed-off-by: Lucas De Marchi …
> am: No backtrace if file doesn't exist

- git_pile/git_pile.py
When creating additional versions of a patch series it's common to pass `-C <previous pile commit>` to reuse the commit message. Do not append the Signed-off-by again if it was already there.
> format: Do not signoff if already signed

- .gitignore
- README.md
- setup.py
- test/common.bash
- test/coverage-shim/git-pile
Implement this in non-intrusive way by defining a shim script that wraps calls to git-pile with `coverage run`. Coverage data can be collected with:
COVERAGE=1 bats test
Then the command `coverage` can be used to generate reports.
NOTE: Another way to implement this would be changing the git-pile script to use coverage API[1] directly. That would result in adding code that would not be used by the end-user and would require some workarounds, like encapsulating the main logic (including the `import git_pile.git_pile as git_pile` statement) into a function, which would have to be called after we tell coverage to start recording data. Because of that, prefer to use the shim-based approach.
[1] https://coverage.readthedocs.io/en/6.5.0/api.html#api
> test: Add support for using coverage

- git_pile/pile.py
The `--format` option for `git ls-tree` is available as of version 2.36. As we support git>=2.19, do not use that option in the command.
Fixes: 9a8118439e68 ("pile: Add method Pile.baseline()")
Fixes: 359ca73e4e08 ("pile: Add method Pile.validate_structure()")
> pile: Make call to ls-tree backward-compatible

- git_pile/git_pile.py
This call got overlooked when doing the refactor to pass the config object to command functions.
Fixes: 38ad271f5700 ("git-pile: Reuse config object in subcommands")
> am: Fix call to cmd_genbranch()

- git_pile/cli.py
- git_pile/git_pile.py
- git_pile/helpers.py
Dump of message from the commit titled `cli: Add module`, which gives the rationale for the changes:
```
Currently git_pile.py is a very long script and adding more features
would mean making it even longer and somewhat cumbersome to
maintain/navigate.
It would be nice to have separate modules for some (if not all)
commands, specially those with long/complex implementations, however the
current code does not provide an easy or natural way of doing so.
As a step into that direction, implement a module providing facilities
for implementing git-pile commands.  While at it, incorporate common
things already being done in `git_pile.py`.
The next patches should change the code to use this new module.  The
transition will bring the following key benefits:
1) This will make it easier to move …
```
> Add module to help definition of pile commands

- git_pile/git_pile.py
- test/40_genlinear_branch.bats
[igt-gpu-tools]$ git pile genlinear-branch -b internal-linear
Traceback (most recent call last):
File "/home/adixit/.local/bin/git-pile", line 4, in <module>
__import__('pkg_resources').run_script('git-pile==1.0.dev0', 'git-pile')
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 656, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1453, in run_script
exec(code, namespace, namespace)
File "/home/adixit/.local/lib/python3.10/site-packages/git_pile-1.0.dev0-py3.10.egg/EGG-INFO/scripts/git-pile", line 12, in <module>
sys.exit(git_pile.main(*sys.argv[1:]))
File "/home/adixit/.local/lib/python3.10/site-packages/git_pile-1.0.dev0-py3.10.egg/git_pile/git_pile.py", line 2432, in …
> genlinear-branch: Fix missing pile_range

- git_pile/git_pile.py
- git_pile/helpers.py
- test/10_init.bats
- test/40_genlinear_branch.bats
- test/50_setup.bats
Make sure our config commands are worktree-aware. This allows having different piles working in the same git repository with checkout in different paths.
User still needs to set `git config extensions.worktreeConfig true` when using multiple piles.
Fix: #7
> Add worktree-aware pile

- .github/workflows/build.yml
- README.md
- git-pile
- setup.py
Default runner in github-actions is now based on Ubuntu 22.04. There won't be python 3.6 for the new runner since it already reached its EOL: https://peps.python.org/pep-0494/#lifespan. Drop it.
> ci: Drop python 3.6

- git_pile/git_pile.py
- test/50_setup.bats
git worktree add was failing in Ubuntu 20.04 that has git 2.25.x. For some reason it doesn't like the patches directory not ending in a slash. Although this could be fixed on the user side by forcing the slash in the config, there is no harm in adding one directly in git-pile.
This was the only fix needed for running the complete testsuite in that distro under git 2.25. After the fix:
28 tests, 0 failures
> Make git-worktree add compatible with git 2.25

- .github/Dockerfile.ubuntu-22.04
- .github/workflows/build.yml
- .github/workflows/container.yml
As detailed in https://github.com/git-pile/git-pile/pull/103#issuecomment-1336298909, this is the compromise to use our own builds of git without having to build them on every PR. 
Fix: #92
> github: use container for testing different git versions

- git_pile/config.py
- git_pile/genbranch.py
- git_pile/git_pile.py
- git_pile/gitutil.py
- test/00_basic.bats
- test/10_init.bats
- test/11_baseline.bats
- test/20_genpatches.bats
- test/30_genbranch.bats
- test/31_genbranch_caching.bats
- test/40_genlinear_branch.bats
- test/50_setup.bats
- test/60_format_patch_and_am.bats
- test/common.bash
pile.dir is always relative to a result-dir: use that information so git-pile tries to fallback in case commands are called from within the pile checkout.
Fix: #104
> git-pile: Figure out result-dir / pile-dir

- .github/workflows/build.yml
- README.md
- git_pile/git_pile.py
Now that we have worktree-aware configuration, it's time to raise minimum git requirement. The worktree support was added in git 2.20. Currently we report the minimum version is 2.19 due to the addition of git-range-diff. Raising to 2.20 shouldn't be a problem for distros as they either package something older or more recent than that (confirmed with Ubuntu, Fedora, RHEL/Centos and Debian).
> Raise minimum requirement for git

- git_pile/genbranch.py
- test/30_genbranch.bats
Useful to generate the result branch from a previous pile revision without touching the pile checkout. E.g.:
git pile genbranch --rev pile~3
> genbranch: Add option --pile-rev

- git_pile/cli.py
- git_pile/config.py
- git_pile/genbranch.py
- git_pile/git_pile.py
- test/30_genbranch.bats
This is useful for generating the result branch on respositories containing the baseline but not configured for git-pile.
See https://github.com/git-pile/git-pile/pull/111#issuecomment-1473997609 for context.
> genbranch: Allow running without a setup in place

- git_pile/pile.py
Methods of _FileReader expect path components in positional arguments and we are passing the full path string to sha1(). Fix that by extracting the components with pathlib.
Fixes: a7e0f7f25a87 ("pile: Add method Pile.series()")
> pile: Pass path components to reader instance

- git_pile/genbranch.py
- git_pile/pile.py
We use caching for speeding up genbranch execution. As a further optimization, we try to use a git tree for the pile object to avoid recalculating hashes for patch files.
One issue that recently happened was that a patchesdir was passed that belonged to another repository, and that confused genbranch, because it assumed the patchesdir lived in the same repository as the current working directory's.
To fix that, let's modify Pile to accept a rev_repo_path argument to allow it to use a different path as base for an instance created with Pile(rev=...); and have genbranch always passing patchesdir to that argument when doing the optimization aforementioned.
> genbranch: Use patchesdir for repository path in cache logic
